on:
  :push

env:
  NODE_VERSION: '14.x'                # set this to the node version to use

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        yarn install
        yarn run test:lint
        yarn run build --if-present
        yarn run test --if-present
